Stud 266 add filter input for participants
Airbenders-490/AirbendersFE pull request #42
Opened 2022-03-14 02:28 UTC by nouj

User clicks filter icon and TextInput appears, allowing the user to type a class name. After pressing return/enter, the typed class name appears on the label. 

Need to be fixed/adjusted:
-> The label appears on the right of the TextInput (placeholder), but on the prototype it is displayed (more like replaces) the placeholder's position. 
-> The label, as it is a reusable component,  is clickable but I need to add a function which removes label when it is selected.

![image](https://user-images.githubusercontent.com/55245612/158094451-ccdbef72-a5f9-4b4b-8515-0761be3f91f8.png)          
![image](https://user-images.githubusercontent.com/55245612/158094544-36aca9a6-c4fd-4cdd-a39b-0b78096fcd4c.png)

2022-03-15 01:49 UTC, car12lin12 reviewed
Can you add a magnifying glass icon next to the filter icon or make the search field a different colour so it's clear where to search? like this:
 <img src="https://user-images.githubusercontent.com/43888017/158289791-0e5916d4-10b6-4ca3-8633-ed0eca25c03c.png" width="300"  />

2022-03-16 01:17 UTC, yasfahm commented
Can you also clear the TextInput on submit? So that we don't see the class name twice!!

2022-03-16 01:17 UTC, yasfahm commented
Can you also clear the TextInput on submit? So that we don't see the class name twice!!

2022-03-17 01:29 UTC, nouj commented
> Can you add a magnifying glass icon next to the filter icon or make the search field a different colour so it's clear where to search? like this: <img alt="" width="300" src="https://user-images.githubusercontent.com/43888017/158289791-0e5916d4-10b6-4ca3-8633-ed0eca25c03c.png">

This is part of another task, STUD-264, which is currently in progress. :)

2022-03-17 01:30 UTC, yasfahm commented on src/screens/Teams.js
> +  handleSubmit = () => {
Can you clear the TextInput on submit? So that we don't see the class name twice!!

2022-03-17 01:31 UTC, nouj commented on src/screens/Teams.js
> +  handleSubmit = () => {
Done!!

2022-03-18 22:30 UTC, car12lin12 commented on src/screens/Teams.js
> +        return <ClassLabel labelColor="#5089E9" labelIcon={XIcon}><LabelClassName>{this.state.className}</LabelClassName></ClassLabel>;
can you add a function to handle the label when you press on the x to cancel the label? right now it turns grey and there's no way to remove the label.

<img src="https://user-images.githubusercontent.com/43888017/159092290-e8666db2-a2a0-44a5-9065-8f9692914bed.png" width="200" />

2022-03-21 22:32 UTC, car12lin12 requested changes
Excellent work Nouj!! I left a few comments addressing unexpected behaviours, let me know if you have questions

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +    console.log("Nouj");
can you remove this? or console log "deleted"

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +    //let {isReady} = this.state;
can remove this?

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +      deleteLabel: true,
can you rename to showLabel? 
Also I think you need to change showLabel to false upon initialization, I see an empty label with just an x when I start the app:
<img src="https://user-images.githubusercontent.com/43888017/159364375-6c6b4ab6-afef-43b6-902a-edf862538a8c.png" width="250" />

Desired behaviour upon initialization:
<img src="https://user-images.githubusercontent.com/43888017/159364904-35dbbcda-9427-4213-8432-c02be0e76b24.png" width="250" />

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +    this.setState({deleteLabel : !this.state.deleteLabel});
can you do setState({showLabel: false}) so it's clear it should always be set to false when you call the deleteLabel method?

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +      this.setState({deleteLabel : !this.state.deleteLabel});
can you do this.setState({showLabel: true}) instead, it should always be true anyway when you call this handleSubmit()?  I say this bc unexpected behaviour can occur if we toggle the boolean here, what if you submit (sets showLabel: true) then call handleSubmit() method again to change the label (sets showLabel: false) so the label isn't shown anymore when it should be shown


right after the above setState, can you also add another this.setState({className: even.nativeEvent.text}) to save the final text submitted. Currently when changing the class name while a label is still showing, we see this:
<img src="https://user-images.githubusercontent.com/43888017/159363837-1f334e54-7665-4846-92aa-c65be4ecaecc.png" width="250" />

But after these changes that will set the className upon submission, the desired behaviour can be achieved:
<img src="https://user-images.githubusercontent.com/43888017/159365146-342162bc-f755-4631-9c71-bf3a5b15b7e0.png" width="250" />

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +  handleSubmit = () => {
can you change the signature to handleSubmit = (event) => {
so that we can take advantage of onSubmitEditing's nativeEvent when setting classEntered

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +  handleClass = (text) => {
can you remove this method since we will set the className in handleSubmit instead?

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +                value={this.state.className}
after the above changes, value can be removed

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +                onChangeText={this.handleClass}
after the above changes, onChangeText can be removed

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +    let {deleteLabel} = this.state;
deleteLabel -> showLabel

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +      if(deleteLabel) {
deleteLabel -> showLabel

2022-03-21 22:32 UTC, car12lin12 commented on src/screens/Teams.js
> +        return <TouchableOpacity onPress={() => this.deleteLabel()} ><ClassLabel isReadOnly = {this.showName} >{deleteLabel ? <LabelClassName>{this.state.className}</LabelClassName> : <View>{null}</V
deleteLabel -> showLabel for the boolean, not the method deleteLabel()

2022-03-22 23:59 UTC, car12lin12 approved these changes
Fantastic work Nouj!! :rocket:

2022-03-23 00:00 UTC, yasfahm approved these changes

2022-03-23 01:02 UTC, merged