Messages websockets
Airbenders-490/AirbendersFE pull request #61
Opened 2022-03-31 10:34 UTC by nuzurie

Connections:
* Receive messages (both new and get updates on screen when others edit and delete messages)
* Edit your own messages 
* Delete your own messages

2022-03-31 23:07 UTC, car12lin12 requested changes
Great job merging guys! A few changes are needed for unexpected behaviors

2022-03-31 23:07 UTC, car12lin12 commented on src/screens/Messages/Tabs/TeamChat.js
> -            getChatRooms: this.getChatRooms
please add [getChatRooms ](https://github.com/Airbenders-490/AirbendersFE/blob/bdaaa94673ad64e7d8758a74479a50e394b9757e/src/screens/Messages/Tabs/TeamChat.js#L74) back, it is needed for accept join request

2022-03-31 23:07 UTC, car12lin12 commented on src/screens/Classes.js
> +class Classes extends Component {
where do we use this component?

2022-03-31 23:07 UTC, car12lin12 commented on src/screens/Messages/MessageTabs.js
> -              marginTop: theme.SPACING_LARGE, /* temporary marginTop */
can you add marginTop back? it is very far to the top on my smaller android screen

2022-03-31 23:07 UTC, car12lin12 commented on src/screens/Messages/Tabs/TeamChat.js
> -        let user = await AsyncStorage.getItem("userID")
can you add [userID ](https://github.com/Airbenders-490/AirbendersFE/blob/bdaaa94673ad64e7d8758a74479a50e394b9757e/src/screens/Messages/Tabs/TeamChat.js#L81) back please

2022-03-31 23:10 UTC, nuzurie commented on src/screens/Messages/Tabs/TeamChat.js
> -            getChatRooms: this.getChatRooms
oops

2022-03-31 23:23 UTC, yasfahm commented on src/screens/Classes.js
> +class Classes extends Component {
this component can be removed

2022-04-01 00:03 UTC, car12lin12 approved these changes
:rocket::rocket:

2022-04-01 21:40 UTC, nuzurie commented on src/screens/Classes.js
> +class Classes extends Component {
Idk where it was added (there are like 100 commits here). But @stellakimnguyen wanted to work on the app after the deadline and might want to use this.

2022-04-01 21:55 UTC, yasfahm commented on src/screens/Classes.js
> +class Classes extends Component {
You can remove this entirely because we replaced it with Teams.js

2022-04-01 21:58 UTC, yasfahm approved these changes

2022-04-02 00:53 UTC, car12lin12 approved these changes

2022-04-02 01:09 UTC, merged