Add test to profile page
Airbenders-490/AirbendersFE pull request #66
Opened 2022-04-02 07:02 UTC by vithura14

2022-04-02 19:22 UTC, car12lin12 requested changes
Great job Vithu :smile: I noticed you committed changes from App.js and TeamChat.js, even though used for testing, the changes cannot be kept for regular app usage. Can we remove the changes and still keep the auto generated reports?

2022-04-02 19:22 UTC, car12lin12 commented on src/screens/Messages/Tabs/TeamChat.js
> +        let userID = "eaf54fae-1ab8-4b5a-8047-51904f6ae884"
do these need to be changed for the reports to be generated? It shouldn't be changed for the actual app, but only for testing

2022-04-02 19:22 UTC, car12lin12 commented on App.js
> +import AsyncStorage from '@react-native-async-storage/async-storage';
please remove all changes to App.js for regular app usage

2022-04-03 16:42 UTC, vithura14 commented
> Great job Vithu 😄 I noticed you committed changes from App.js and TeamChat.js, even though used for testing, the changes cannot be kept for regular app usage. Can we remove the changes and still keep the auto generated reports?

Yes definitely! Will address your PR comments right away!

2022-04-03 21:28 UTC, car12lin12 approved these changes

2022-04-04 00:46 UTC, merged